pull_request: ''
jobs: ''
run: |-
  "cd ctest
  ./main
  "
branches: ''
'---': ''
'-': 'name: ''Run C program'''
steps: ''
push: ''
'''on''': ''
runs-on: '''ubuntu-latest'''
build: ''
name: '''C Build and Run'''
uses: '''actions/checkout@v4'''
