name: C Build and Run

on:
  push:
    branches: ["main", "mai"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile C program
        run: gcc main.c -o main

      - name: Run program
        run: ./main

      - name: Compile C program
        run: gcc main.c -o main

      - name: Run program
        run: ./main
